title: 歸巢
description: 我會在這裡寫下更長的東西！
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
show_excerpts: true
timezone: Asia/Taipei
nav:
  - name: 首頁
    link: /
  - name: 文章
    link: /blog
  - name: 標籤
    link: /tags
  - name: 關於
    link: /about
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
defaults:
  - scope:
      path: ""        # 站內全部路徑
      type: "posts"   # 只套用在文章
    values:
      layout: post-with-nav
