title: 歸巢
description: 我會在這裡寫下更長的東西！
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
show_excerpts: true
timezone: Asia/Taipei
nav:
  - name: 首頁
    link: /
  - name: 文章
    link: /blog
  - name: 分類
    link: /categories
  - name: 關於
    link: /about
