backend:
  name: github
  repo: lienacreator1214/lienacreator1214.github.io
  branch: main
  base_url: https://decap-oauth-node.onrender.com
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈時間", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ" }
      - { label: "版型", name: "layout", widget: "hidden", default: "with-nav" }
      - { label: "內容", name: "body", widget: "markdown" }
