backend:
  name: github
  repo: lienacreator1214/lienacreator1214.github.io
  branch: main
  base_url: https://decap-oauth-node.onrender.com
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "categories"
    label: "分類"
    label_singular: "分類"
    folder: "_categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "名稱", name: "title", widget: "string", hint: "例如：生活、技術、隨筆" }

  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }

      # 分類：改用 Jekyll 原生的複數 key，並允許多選
      - label: "分類"
        name: "categories"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
        multiple: true
        required: false

      # 標籤：使用 list，任意新增
      - { label: "標籤", name: "tags", widget: "list", default: [] }
      - { label: "內文", name: "body", widget: "markdown" }
